fixup! WIP: Make gencert support OpenSSL

diff --git a/sbin/gencert b/sbin/gencert
--- a/sbin/gencert
+++ b/sbin/gencert
@@ -26,8 +26,12 @@ GENCERT_REALM=
 GENCERT_KEY_BITS=2048
 GENCERT_INCLUDE_SAN_PKINIT=true
 GENCERT_INCLUDE_SAN_DNSNAME=false
-GENCERT_EKUS=()
+GENCERT_X509_TOOLING=OpenSSL # Or Heimdal
+declare -a GENCERT_EKUS
 declare -A GENCERT_DOMAIN_REALM
+declare -A POLICIES
+GENCERT_EKUS=()
+GENCERT_DOMAIN_REALM=()
 
 if [[ -n ${SAFEBOOT_ENROLL_CONF:-} ]]; then
 	# shellcheck disable=SC1090
@@ -102,7 +106,7 @@ extendedKeyUsage=@eku_section
 subjectKeyIdentifier=hash
 authorityKeyIdentifier=keyid,issuer
 issuerAltName=issuer:copy
-subjectAltName = @subject_alt_section
+subjectAltName=critical,@subject_alt_section
 
 [eku_section]
 extendedKeyUsage=1.3.6.1.5.2.3.4
@@ -119,7 +123,7 @@ $(${GENCERT_INCLUDE_SAN_PKINIT}		\
 	&& printf 'otherName.2=1.3.6.1.5.2.2;SEQUENCE:princ_name\n')
 
 [princ_name]
-realm=EXP:0,GeneralString:${ENV::REALM}
+realm=EXP:0,GeneralString:\${ENV::GENCERT_REALM}
 principal_name=EXP:1,SEQUENCE:principal_seq
 
 [principal_seq]
@@ -127,35 +131,48 @@ name_type=EXP:0,INTEGER:1
 name_string=EXP:1,SEQUENCE:principals
 
 [principals]
-princ0=GeneralString:${ENV::SERVICE}
-princ1=GeneralString:${ENV::HOST_NAME}
+princ0=GeneralString:\${ENV::SERVICE}
+princ1=GeneralString:\${ENV::HOST_NAME}
 EOF
 
 # Generate the private key (and a CSR, which is kind of unnecessary, but...)
 trap 'rm -f cert-extensions cert-req cert-key.pem' EXIT
 
 # Try Heimdal's hxtool
-if ! hxtool request-create						\
-	--subject=''							\
-	--generate-key=rsa						\
-	--key-bits="$GENCERT_KEY_BITS"					\
-	--key="PEM-FILE:cert-key.pem"					\
-	cert-req 2>/dev/null						\
-    || ! hxtool issue-certificate					\
-	"${hxtool_ca_opts[@]}"						\
-	--type=pkinit-client						\
-	--subject=							\
-	--ku=digitalSignature						\
-	--lifetime=10y							\
-	--req="PKCS10:cert-req"						\
-	--certificate=PEM-FILE:cert.pem 2>/dev/null; then
-
-	# Try OpenSSL
-	openssl genrsa -out cert-key.pem 2048				\
+case "$GENCERT_X509_TOOLING" in
+Heimdal)
+	hxtool request-create						\
+		--subject=''						\
+		--generate-key=rsa					\
+		--key-bits="$GENCERT_KEY_BITS"				\
+		--key="PEM-FILE:cert-key.pem"				\
+		cert-req 2>/dev/null					\
+	|| die "Could not generate a key and make a CSR"
+	! hxtool issue-certificate					\
+		"${hxtool_ca_opts[@]}"					\
+		--type=pkinit-client					\
+		--subject=						\
+		--ku=digitalSignature					\
+		--lifetime=10y						\
+		--req="PKCS10:cert-req"					\
+		--certificate=PEM-FILE:cert.pem 2>/dev/null		\
+	|| die "Could not issue certificate"
+	;;
+OpenSSL)
+	openssl genrsa							\
+		-out cert-key.pem 2048					\
 	|| die "Could not make an RSA key"
-	openssl req -new -key cert-key.pem -out client.req		\
+	openssl req							\
+		-new							\
+		-batch							\
+		-key cert-key.pem					\
+		-out client.req						\
 	|| die "Could not make a CSR"
-	env REALM="$GENCERT_REALM" HOST_NAME="$hostname" SERVICE="host"	\
+
+	export GENCERT_REALM
+	export HOST_NAME="$hostname"
+	export SERVICE="host"
+
 	openssl x509							\
 		-set_serial "0x$(_rand 16 | bin2hex)"			\
 		"${openssl_x509_opts[@]}"				\
@@ -165,13 +182,13 @@ if ! hxtool request-create						\
 		-extfile cert-extensions				\
 		-days 365						\
 		-out client.pem						\
-	|| die "Could not make a certificate with either Heimdal's hxtool(1) nor OpenSSL's openssl-x509(1)"
-fi
+	|| die "Could not make a certificate"
+esac
 
 
 # Append the issuer certificate and any other certs in that file to the output
 # so that the full chain is included.
-openssl crl2pkcs7 -nocrl -certfile "${GENCERT_CRED#*:}"		\
+openssl crl2pkcs7 -nocrl -certfile "${GENCERT_CA_CERT#*:}"		\
 | openssl pkcs7 -print_certs >> cert.pem
 
 grep -q PRIVATE cert.pem && die "Private key in cert file?!"
